coef_CS <- utils::getFromNamespace("coef_CS", "clubSandwich")
model_matrix <- utils::getFromNamespace("model_matrix", "clubSandwich")
residuals_CS <- utils::getFromNamespace("residuals_CS", "clubSandwich")
matrix_list <- utils::getFromNamespace("matrix_list", "clubSandwich")
weightMatrix <- utils::getFromNamespace("weightMatrix", "clubSandwich")
v_scale <- utils::getFromNamespace("v_scale", "clubSandwich")
